spring:
  datasource:
    url: jdbc:h2:mem:ordersdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    driverClassName: org.h2.Driver
    username: sa
    password: ""
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
  h2:
    console:
      enabled: true

  temporal:
    connection:
      target: local
    workers:
      - name: orderWorker
        task-queue: order-saga-tq
        workflow-classes:
          - com.arashrostami.temporalsaga.workflow.impl.OrderSagaWorkflowImpl
        activity-beans:
          - inventoryActivitiesImpl
          - paymentActivitiesImpl
          - shippingActivitiesImpl
          - orderActivitiesImpl

logging:
  level:
    root: info
